---
title: "CUNY SPS Data 607 Project 2"
output: html_notebook
references:
- id: StatCan
  title: Labour force characteristics, monthly, seasonally adjusted and trend-cycle, last 5 months
  URL: 'https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=1410028701'
  DOI: https://doi.org/10.25318/1410028701-eng
  publisher: Statistics Canada
  type: website
---


# Introduction

The goal of Project 2 is to choose 3 wide datasets and transform the datasets
- Create a .CSV file (or optionally, a MySQL database!) that includes all of the information included in the dataset.  You’re encouraged to use a “wide” structure similar to how the information appears in the discussion item, so that you can practice tidying and transformations as described below.
- Read the information from your .CSV file into R, and use tidyr and dplyr as needed to tidy and transform your data.  [Most of your grade will be based on this step!]
- Perform the analysis requested in the discussion item.
- Your codeshould be in an R Markdown file, posted to rpubs.com, and should include narrative descriptions of your data cleanup work, analysis,and conclusions.

# Dataset 1 : Canada Unemployment Rate

The dataset that is from Stat Canada which is a government organization which compiles data for the public. The dataset that we will be looking at is the Canada unemployment data [@StatCan]. We can see that this is a wide dataset with all of the months being in the columns. The CSV file also includes a lot of unnecessary information that needs to be cleaned before any analysis can be done on the dataset. 

# References
